### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by SamuelMathieu-code** [VorontsovIE/macro-perfectos-ape#1]
Hi,

I had an issue when using ape.jar latest version (my input is to big to use the Web API) :
I am absolutely not familiar with Java as I tend to program mainly with Julia and python so I'd need your help.

I use Java 17.0.12 on ubuntu 22.04.

```
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```
and I got this error :

```
Exception in thread "main" java.lang.IllegalAccessError: class ru.autosome.commons.importer.MotifImporter (in unnamed module @0x26ee6b5e) cannot access class sun.reflect.generics.reflectiveObjects.NotImplementedException (in module java.base) because module java.base does not export sun.reflect.generics.reflectiveObjects to unnamed module @0x26ee6b5e
        at ru.autosome.commons.importer.MotifImporter.loadMotifCollectionWithNamesFromFile(MotifImporter.java:85)
        at ru.autosome.commons.importer.MotifImporter.loadMotifCollectionWithNames(MotifImporter.java:64)
        at ru.autosome.perfectosape.SNPScan.load_collection_of_pwms(SNPScan.java:39)
        at ru.autosome.perfectosape.cli.generalized.SNPScan.load_collection_of_pwms_with_evaluators(SNPScan.java:40)
        at ru.autosome.perfectosape.cli.generalized.SNPScan.setup_from_arglist(SNPScan.java:182)
        at ru.autosome.perfectosape.cli.generalized.SNPScan.setup_from_arglist(SNPScan.java:154)
        at ru.autosome.perfectosape.SNPScan.from_arglist(SNPScan.java:48)
        at ru.autosome.perfectosape.SNPScan.main(SNPScan.java:54)
```

when using this command :

```
java -cp ape.jar  ru.autosome.perfectosape.SNPScan hocomoco/all.txt input_perfectosAPE.txt > out_file
```
hocomoco/all.txt is formated as follows : (just concat of all hocomoco pwms in the all_collections_package)

```
AHR_si
0.049659785047587994    -0.7112292711652767     0.37218581437481474     0.007118345755727385
-1.1863517717347103     -1.1076775894500097     -0.10122262270572081    0.9004092051347219
-0.5481419620395537     0.1272377147320841      -0.59308886562888       0.5502420250441404
-2.3460850844035765     -2.7362137930742176     1.3086872088653378      -1.979560121872744
-3.4521272549574107     1.3387809407527809      -2.670269442762781      -2.4686685687477508
-2.13497354677774       -2.965000508388953      1.332280817276548       -3.206089427067849
-3.4521272549574107     -2.13497354677774       -3.0087911229263216     1.3351912597409432
-3.4521272549574107     -3.4521272549574107     1.3622489404156517      -3.4521272549574107
0.10927007207680553     0.538906490155854       -0.8250174241334565     -0.31173208856325346
AIRE_f2
0.43313006490651174     0.04085227918631347     -0.6137453250557839     -0.1336395596338073
-0.287934480342677      -0.287934480342677      -0.5395374528181144     0.6509496053482315
-0.5395374528181144     -0.5395374528181144     -0.18247299388319277    0.6935256729807076
-1.3885683289744977     -2.4932699340361553     1.204502653612288       -1.1001276925450065
-2.4932699340361553     -2.4932699340361553     1.1265227050987685      -0.287934480342677
0.22329496547372982     -1.3885683289744977     -1.795552293481534      0.847730411461277
0.40571745230539336     -0.8765292788918836     -1.795552293481534      0.6509496053482315
0.34852935421768405     -0.5395374528181144     -0.5395374528181144     0.34852935421768405
0.28787133656922687     -1.1001276925450065     -0.5395374528181144     0.5599402187803801
0.6935256729807093      -0.8765292788918836     -0.5395374528181144     0.0
0.40571745230539336     -1.3885683289744977     -1.1001276925450065     0.6509496053482315
-0.08708020918724992    -0.5395374528181144     -1.1001276925450065     0.7735974895230041
-2.4932699340361553     -1.795552293481534      1.204502653612288       -0.8765292788918836
-2.4932699340361553     -2.4932699340361553     1.2998334712143398      -1.795552293481534
-0.08708020918724992    -0.8765292788918836     0.0     0.5111284291622553
-1.1001276925450065     -0.287934480342677      -0.287934480342677      0.7735974895230041
0.5599402187803783      -1.795552293481534      -0.4058437438396847     0.34852935421768405
0.4465596316108243      0.060669157772702556    -0.7365300991442317     -0.11008893724295123
...
```

Hope you can help!

Sam

**Comment by SamuelMathieu-code** [comment]
ERROR solved : 
Error message was not clear because of java version. I used https://anaconda.org/bioconda/java-jdk instead and figured out the motifs needed to be in a folder with one file per motif.

**Comment by VorontsovIE** [comment]
@SamuelMathieu-code Dear Samuel, Sorry that wasn't able to respond to you earlier, and glad that you figured out the way to run APE.
Do you have any other questions?
